pad.go
tb.go

Implement the TB struct for registration protocol. 
* Part of #13 
* Currently TB implementation is being used in https://github.com/coniks-sys/libconiks-server-go/blob/registration/coniks/handler.go#L45-L47

Temporary Binding implementation

---

crypto/ed25519/extra25519/extra25519_test.go
crypto/vrf/vrf.go
crypto/vrf/vrf_test.go
merkletree/merkletree.go
merkletree/merkletree_test.go
merkletree/pad.go
merkletree/pad_test.go
merkletree/policy.go
merkletree/proof.go
merkletree/proof_test.go

Use coname's vrf implementation to compute the private index
- Should resolve #14 
- commented out parts of a test which is supposed to work with a specific hash (but not with vrf); might be changed with #16 and #18
- replaced `t.Error` in combination with `return` with `t.Fatal`

Vrf integration

---

merkletree/README.md
merkletree/policy.go

Rename DefaultPolicies to ConiksPolicies

---

merkletree/merkletree.go
merkletree/merkletree_test.go
merkletree/pad.go
merkletree/pad_test.go
merkletree/policy.go
merkletree/proof.go
merkletree/proof_test.go
merkletree/str.go
merkletree/tb.go

~~Golang code should not use getters and setters rather than struct fields.~~ This pull removes all getters from `STR`, `AuthenticationPath`, `TemporaryBinding` and `DefaultPolicies` struct.
/cc @arlolra @masomel @Liamsi

Remove all getters

---

.gitignore
README.md
client/cgo/Makefile
client/cgo/cgotest.go
client/cgo/verification.go
client/cgo/verification_test.go
crypto/sign/sign.go
crypto/sign/sign_test.go
crypto/util_test.go
merkletree/pad_test.go
merkletree/proof_test.go
merkletree/str.go
utils/util_test.go

I merged branch `no-getset` since we can take the advantages of struct fields (e.g., https://github.com/coniks-sys/coniks-go/blob/9c253690f74c41d9763111bd660cbb8108236b86/client/cgo/coniks.go#L105-L107). 
I will fixed other getters when the #36 is clarified.

Client library for verifications

---

crypto/sign/sign_test.go
crypto/util_test.go
merkletree/pad_test.go
merkletree/proof_test.go
merkletree/str.go
utils/util_test.go

Stress tests

---

client/cgo/cgotest.go
crypto/sign/sign.go
crypto/sign/sign_test.go
merkletree/pad_test.go
merkletree/policy.go
utils/coname.go
utils/util.go

This pull is a part of #29. It includes following changes:
* Remove unnecessary method from `merkletree/policy.go`.
* Add new functions to `util` package.
* `sign.GenerateKey` should take a reader as `vrf`.

Remove unnecessary Policies's method & add new util functions

---

client/cgo/cgotest.go
client/cgo/verification.go
crypto/sign/sign.go
crypto/sign/sign_test.go
crypto/vrf/vrf.go
crypto/vrf/vrf_test.go
merkletree/merkletree_test.go
merkletree/pad.go
merkletree/policy.go

- change underlying type for vrf keys to slice of bytes instead of arrays
- GenerateKey in `vrf` and `sign` package have equivalent signatures
- in `vrf` and `sign` `Public()` returns a vrf/sign `PublicKey` type
- deleted `Serialize()` ~~returns a slice of byte~~
Should resolve #65

Align sign and vrf package

---

.gitignore
.travis.yml
keyserver/README.md
keyserver/coniksserver/cmd/init.go
keyserver/coniksserver/cmd/root.go
keyserver/coniksserver/cmd/run.go
keyserver/coniksserver/coniksserver.go
keyserver/encoding.go
keyserver/listener.go
keyserver/server.go
keyserver/server_test.go
keyserver/testutil/testutil.go
merkletree/policy.go
protocol/directory.go
protocol/error.go
protocol/message.go
utils/util.go

* Implement registration function

Implement reference key server

---

.travis.yml
keyserver/listener.go
keyserver/testutil/testutil.go

This should prevent the need for `DynamicRecordSizingDisabled`
I don't think you intended to keep long living tcp connections.  If we want them, we probably need a protocol above that layer, even if it's just sending the length to read in the first byte.

CloseWrite to indicate end

---

keyserver/encoding.go
keyserver/server_test.go
keyserver/testutil/testutil.go
protocol/directory.go
protocol/directory_test.go
protocol/message.go

- Convert `Response` interface to a struct like `Request`
- Refactor server_test.go code

Convert Response interface to struct

---

protocol/directory.go

If the developers want to query `EpochDeadline` before the new policies is updated, `ConiksDirectory.EpochDeadline()` should return the `EpochDeadline` from the pad's policies instead of the current policies of the directory.

ConiksDirectory.EpochDeadline() should return EpochDeadline from the PAD's Policies

---

merkletree/pad.go
merkletree/policy.go
protocol/directory.go
protocol/directory_test.go

Remove `Policies` interface and use `ConiksPolicies` struct instead.

Remove Policies interface

---

protocol/directory.go
protocol/directory_test.go

Panic if the server does not use TBs

---

keyserver/coniksserver/cmd/init.go
keyserver/coniksserver/cmd/run.go
keyserver/listener.go
keyserver/server.go
keyserver/server_test.go
keyserver/testutil/testutil.go

Which do you prefer:
- Set `LocalAddress` to an empty string to disable the registration bot
- Or, have a `IsUseBot` field in `ServerConfig`?

Make the usage of the registration bot configurable

---

crypto/internal/ed25519/edwards25519/const.go
crypto/vrf/vrf.go
crypto/vrf/vrf_test.go

Adopt VRF to update in CONIKS paper  …
- add unique identifier: also hash h=H1(m), g^x and h^x (the VRF output) and not only with random nonce r (g^r, h^r); additionally hash m into H2 (as before)
- like in the paper add the base-point and public-key
- skip outdated test-vectors
- renamed some vars according to naming in the paper
- unrelated: remove formatting version of test-output where no placeholder is used
fixes #175

Vrf uniqueness was violated (quickfix)

---

protocol/auditlog.go
protocol/auditlog_test.go
protocol/common.go
protocol/common_test.go
protocol/consistencychecks.go
protocol/error.go
protocol/message.go
protocol/str.go
protocol/testutil.go

Client-auditor protocol

---

client/encoding.go
client/encoding_test.go
keyserver/server_test.go
keyserver/testutil/testutil.go
protocol/consistencychecks.go
protocol/directory_test.go
protocol/message.go

A series of pulls towards #173.

Merge `DirectoryProof` and `DirectoryProofs` into one

---

protocol/auditlog.go
protocol/auditlog_test.go
protocol/auditor.go
protocol/auditor_test.go
protocol/consistencychecks.go
protocol/consistencychecks_test.go
protocol/directory.go
protocol/directory_test.go
protocol/message.go
protocol/str_test.go
protocol/testutil.go

Implement auditor-server protocol

---

README.md

the original command:
```
go get github.com/coniks-sys/coniks-go/...
```
results in
```
riselab@riselab-Inspiron-5559:~$ go get github.com/coniks-sys/coniks-go
can't load package: package github.com/coniks-sys/coniks-go: no Go files in /home/riselab/go/src/github.com/coniks-sys/coniks-go
```
I think maybe we should add `...`?

Seems latest `go get` needs to add `...`

---

.travis.yml
application/client/config.go
application/config.go
application/encoding.go
application/server/config.go
application/server/server.go
cli/coniksclient/internal/cmd/init.go
cli/coniksclient/internal/cmd/run.go
cli/coniksserver/internal/cmd/init.go

Addresses #196 
Mechanism:
* Add STR serialization/de-serialization functions
* Serialize the key server's initial STR to disk upon startup
* Add initial STR to client config
* Client is initialized with initial STR specified in config
~~Blocked by #203~~

Pin key server initial STR, load in client
